### PR TITLE
ruby 2.2.0

### PR DESCRIPTION
**Pull request by glaszig**
also builds libruby like suggested in #15.

### CODE REVIEW

**Comment by eljojo** [comment]
@bradrydzewski any way to get this through? would be really helpful!

**Comment by glaszig** [comment]
[my images on docker's registry](https://registry.hub.docker.com/u/glaszig/drone-ruby/) may help you in the meantime.

**Comment by eljojo** [comment]
@glaszig is :latest set to 2.2.0/2.2.1?

**Comment by glaszig** [comment]
> is :latest set to 2.2.0/2.2.1?

at 2.1.5, still.

**Pull request closed without merging**
