### PR TITLE
Add node.js v0.12 and iojs

### PR DESCRIPTION
**Pull request by yosuke-furukawa**
drone does not have latest node.js version and iojs.

https://github.com/drone/drone/issues/931

### CODE REVIEW

**Comment by rfink** [comment]
+1

**Comment by yosuke-furukawa** [comment]
@rfink thanks.

@bradrydzewski please check my pull request. if my p-r has some problem, i will fix it.

**Comment by michikono** [comment]
+1

**Comment by olalonde** [comment]
:+1:

**Comment by muddydixon** [comment]
:+1:

**Comment by nel215** [comment]
:+1:

**Comment by fuku2015** [comment]
+1

**Pull request closed without merging**
