### PR TITLE
Add all Python versions for each images #45

### PR DESCRIPTION
**Pull request by cedk**
For #45

### CODE REVIEW

**Comment by bradrydzewski** [comment]
Perhaps adding a single new Dockerfile with all python versions installed:
builder/python/python_all/Dockerfile

It cuts down on the size of the base virtualenv image. It also simplifies adding new python versions since we only have to update python:all

**Comment by cedk** [comment]
But in this case which one will be the default python version?
Or we do all_python:2.7, all_python3.2 etc.

**Comment by cedk** [comment]
FYI, the result images are 400MB bigger.

**Comment by bradrydzewski** [comment]
I was thinking just a single `python:all` image. If the goal is to test all python versions with tox we can just pick a default. What is standard these days in Pythong? 2.7?

**Comment by cedk** [comment]
OK, so I guess we can stick with the default python interpreter of Ubuntu.
I will update the PR according.

**Comment by cedk** [comment]
Here it is. I also added tox to this image as it will be the main tool used.

**Pull request merged**
